In [1]:
import pandas as pd
df = pd.read_csv('../data/raw/financials.csv')
df.head(22)

,Unnamed: 0,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,...,2017-09-01,2018-09-01,2019-09-01,2020-09-01,2021-09-01,2022-09-01,2023-09-01,Nov 2014,2023-05-01,Dec 2010
0,Sales,300.00,312.00,327.00,356.00,357.00,392.00,427.00,480.00,529.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Expenses,264.00,273.00,297.00,326.00,310.00,337.00,367.00,411.00,463.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Operating Profit,36.00,39.00,31.00,30.00,46.00,56.00,60.00,69.00,66.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,OPM %,12.00,12.00,9.00,8.00,13.00,14.00,14.00,14.00,12.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Other Income,2.00,-5.00,2.00,4.00,4.00,2.00,1.00,2.00,3.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Interest,16.00,18.00,24.00,27.00,25.00,24.00,22.00,22.00,22.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Depreciation,7.00,8.00,11.00,11.00,10.00,10.00,10.00,10.00,13.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Profit before tax,16.00,8.00,-2.00,-3.00,14.00,23.00,28.00,38.00,35.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Tax %,29.00,37.00,-19.00,16.00,24.00,31.00,32.00,35.00,30.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Net Profit,11.00,5.00,-2.00,-2.00,11.00,16.00,19.00,25.00,24.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,EPS in Rs,3.85,1.51,-0.68,-0.74,3.11,4.49,5.34,7.08,6.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Sales,NaN,NaN,NaN,NaN,NaN,NaN,1705.00,1578.00,1521.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Expenses,NaN,NaN,NaN,NaN,NaN,NaN,652.00,589.00,698.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Operating Profit,NaN,NaN,NaN,NaN,NaN,NaN,1053.00,990.00,823.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,OPM %,NaN,NaN,NaN,NaN,NaN,NaN,62.00,63.00,54.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Other Income,NaN,NaN,NaN,NaN,NaN,NaN,10.00,1.00,6.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Interest,NaN,NaN,NaN,NaN,NaN,NaN,559.00,431.00,502.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Depreciation,NaN,NaN,NaN,NaN,NaN,NaN,14.00,22.00,41.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Profit before tax,NaN,NaN,NaN,NaN,NaN,NaN,490.00,538.00,286.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Tax %,NaN,NaN,NaN,NaN,NaN,NaN,22.00,30.00,30.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Net Profit,NaN,NaN,NaN,NaN,NaN,NaN,380.00,375.00,201.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,EPS in Rs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.shape

(49401, 113)

In [5]:
df['Unnamed: 0'].unique()

array(['Sales', 'Expenses', 'Operating Profit', 'OPM %', 'Other Income',
       'Interest', 'Depreciation', 'Profit before tax', 'Tax %',
       'Net Profit', 'EPS in Rs', 'Revenue', 'Financing Profit',
       'Financing Margin %'], dtype=object)

In [6]:
df['company_name'].nunique()

4491

In [7]:
df.columns.tolist()

['Unnamed: 0',
 'Mar 2012',
 'Mar 2013',
 'Mar 2014',
 'Mar 2015',
 'Mar 2016',
 'Mar 2017',
 'Mar 2018',
 'Mar 2019',
 'Mar 2020',
 'Mar 2021',
 'Mar 2022',
 'Mar 2023',
 'TTM',
 'company_name',
 '2012-03-01',
 '2013-03-01',
 '2014-03-01',
 '2015-03-01',
 '2016-03-01',
 '2017-03-01',
 '2018-03-01',
 '2019-03-01',
 '2020-03-01',
 '2021-03-01',
 '2022-03-01',
 '2023-03-01',
 'Mar 2011',
 'Dec 2011',
 'Dec 2012',
 'Dec 2013',
 'Dec 2014',
 'Dec 2015',
 'Dec 2016',
 'Dec 2017',
 'Dec 2018',
 'Dec 2019',
 'Dec 2020',
 'Dec 2021',
 'Dec 2022',
 'Mar 2006',
 'Mar 2007',
 'Mar 2008',
 'Mar 2009',
 'Mar 2010',
 'Jan 2023',
 'Jun 2012',
 'Jun 2013',
 'Jun 2014',
 'Jun 2015',
 'Jun 2016',
 'Jun 2017',
 'Jun 2018',
 'Jun 2019',
 'Jun 2020',
 'Jun 2021',
 'Jun 2022',
 'Jun 2023',
 'Sep 2012',
 'Sep 2013',
 'Sep 2018',
 'Sep 2011',
 '2010-03-01',
 '2011-03-01',
 'Sep 2014',
 '2012-09-01',
 '2013-09-01',
 'Sep 2015',
 '2022-02-01',
 '2021-11-01',
 '2009-03-01',
 '2010-06-01',
 '2011-06-01',
 '2012-12-01',
 'Jun 2011',
 'Jun 2006',
 '2006-03-01',
 '2007-03-01',
 '2008-03-01',
 'Sep 2005',
 '2023-02-01',
 '2022-11-01',
 'Jun 2007',
 'Jun 2008',
 'Jun 2009',
 'Jun 2010',
 'Aug 2011',
 'Aug 2012',
 'Aug 2013',
 'Aug 2014',
 '2012-06-01',
 '2014-09-01',
 '2015-09-01',
 'Oct 2012',
 'Oct 2013',
 'Nov 2022',
 'May 2018',
 'Sep 2007',
 '2013-06-01',
 '2004-03-01',
 '2005-03-01',
 'May 2017',
 '2016-09-01',
 '2017-09-01',
 '2018-09-01',
 '2019-09-01',
 '2020-09-01',
 '2021-09-01',
 '2022-09-01',
 '2023-09-01',
 'Nov 2014',
 '2023-05-01',
 'Dec 2010']

In [8]:
df.isnull().sum()

Unnamed: 0        0
Mar 2012      16855
Mar 2013      15926
Mar 2014      14741
Mar 2015      12757
              ...
2022-09-01    49390
2023-09-01    49390
Nov 2014      49392
2023-05-01    49390
Dec 2010      49392
Length: 113, dtype: int64

In [9]:
df['company_name'].nunique()

4491

In [10]:
df[df['company_name'] == 'Reliance Industries Ltd']

,Unnamed: 0,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,...,2017-09-01,2018-09-01,2019-09-01,2020-09-01,2021-09-01,2022-09-01,2023-09-01,Nov 2014,2023-05-01,Dec 2010
34958,Sales,357677.00,395957.00,433521.00,374372.00,272583.00,303954.00,390823.00,568337.00,596679.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34959,Expenses,324501.00,362802.00,398586.00,336923.00,230802.00,257647.00,326508.00,484087.00,507413.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34960,Operating Profit,33176.00,33155.00,34935.00,37449.00,41781.00,46307.00,64315.00,84250.00,89266.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34961,OPM %,9.00,8.00,8.00,10.00,15.00,15.00,16.00,15.00,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34962,Other Income,7526.00,7757.00,8865.00,8528.00,12212.00,9222.00,9869.00,8406.00,8570.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34963,Interest,2893.00,3463.00,3836.00,3316.00,3691.00,3849.00,8052.00,16495.00,22027.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34964,Depreciation,12401.00,11232.00,11201.00,11547.00,11565.00,11646.00,16706.00,20934.00,22203.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34965,Profit before tax,25408.00,26217.00,28763.00,31114.00,38737.00,40034.00,49426.00,55227.00,53606.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34966,Tax %,22.00,20.00,22.00,24.00,23.00,25.00,27.00,28.00,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34967,Net Profit,19717.00,20886.00,22548.00,23640.00,29861.00,29833.00,36080.00,39837.00,39880.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34968,EPS in Rs,28.26,30.31,32.62,34.14,43.03,43.11,53.39,58.55,58.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
pd.set_option('display.max_columns', None)
df[df['company_name'] == 'Reliance Industries Ltd']

,Unnamed: 0,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,Mar 2021,Mar 2022,Mar 2023,TTM,company_name,2012-03-01,2013-03-01,2014-03-01,2015-03-01,2016-03-01,2017-03-01,2018-03-01,2019-03-01,2020-03-01,2021-03-01,2022-03-01,2023-03-01,Mar 2011,Dec 2011,Dec 2012,Dec 2013,Dec 2014,Dec 2015,Dec 2016,Dec 2017,Dec 2018,Dec 2019,Dec 2020,Dec 2021,Dec 2022,Mar 2006,Mar 2007,Mar 2008,Mar 2009,Mar 2010,Jan 2023,Jun 2012,Jun 2013,Jun 2014,Jun 2015,Jun 2016,Jun 2017,Jun 2018,Jun 2019,Jun 2020,Jun 2021,Jun 2022,Jun 2023,Sep 2012,Sep 2013,Sep 2018,Sep 2011,2010-03-01,2011-03-01,Sep 2014,2012-09-01,2013-09-01,Sep 2015,2022-02-01,2021-11-01,2009-03-01,2010-06-01,2011-06-01,2012-12-01,Jun 2011,Jun 2006,2006-03-01,2007-03-01,2008-03-01,Sep 2005,2023-02-01,2022-11-01,Jun 2007,Jun 2008,Jun 2009,Jun 2010,Aug 2011,Aug 2012,Aug 2013,Aug 2014,2012-06-01,2014-09-01,2015-09-01,Oct 2012,Oct 2013,Nov 2022,May 2018,Sep 2007,2013-06-01,2004-03-01,2005-03-01,May 2017,2016-09-01,2017-09-01,2018-09-01,2019-09-01,2020-09-01,2021-09-01,2022-09-01,2023-09-01,Nov 2014,2023-05-01,Dec 2010
34958,Sales,357677.00,395957.00,433521.00,374372.00,272583.00,303954.00,390823.00,568337.00,596679.0,466307.0,698672.00,876396.00,869443.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34959,Expenses,324501.00,362802.00,398586.00,336923.00,230802.00,257647.00,326508.00,484087.00,507413.0,385517.0,588077.00,734078.00,716779.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34960,Operating Profit,33176.00,33155.00,34935.00,37449.00,41781.00,46307.00,64315.00,84250.00,89266.0,80790.0,110595.00,142318.00,152664.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34961,OPM %,9.00,8.00,8.00,10.00,15.00,15.00,16.00,15.00,15.0,17.0,16.00,16.00,18.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34962,Other Income,7526.00,7757.00,8865.00,8528.00,12212.00,9222.00,9869.00,8406.00,8570.0,22432.0,17928.00,12020.00,13997.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34963,Interest,2893.00,3463.00,3836.00,3316.00,3691.00,3849.00,8052.00,16495.00,22027.0,21189.0,14584.00,19571.00,22588.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34964,Depreciation,12401.00,11232.00,11201.00,11547.00,11565.00,11646.00,16706.00,20934.00,22203.0,26572.0,29797.00,40303.00,45999.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34965,Profit before tax,25408.00,26217.00,28763.00,31114.00,38737.00,40034.00,49426.00,55227.00,53606.0,55461.0,84142.00,94464.00,98074.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34966,Tax %,22.00,20.00,22.00,24.00,23.00,25.00,27.00,28.00,26.0,3.0,19.00,22.00,NaN,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34967,Net Profit,19717.00,20886.00,22548.00,23640.00,29861.00,29833.00,36080.00,39837.00,39880.0,53739.0,67845.00,74088.00,77269.00,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34968,EPS in Rs,28.26,30.31,32.62,34.14,43.03,43.11,53.39,58.55,58.2,77.5,89.74,98.59,101.25,Reliance Industries Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN