In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/financials.csv")

In [3]:
df.shape

(49401, 113)

In [4]:
df = df.rename(columns={"Unnamed: 0": "metric"})

In [5]:
df.columns[:5]

Index(['metric', 'Mar 2012', 'Mar 2013', 'Mar 2014', 'Mar 2015'], dtype='object')

In [6]:
year_columns = [
    'Mar 2012','Mar 2013','Mar 2014',
    'Mar 2015', 'Mar 2016', 'Mar 2017',
'Mar 2018', 'Mar 2019', 'Mar 2020',
'Mar 2021', 'Mar 2022', 'Mar 2023']

In [7]:
cols_to_keep = ['metric','company_name'] + year_columns

In [8]:
df_filtered = df[cols_to_keep]

In [9]:
df_filtered.head(11)

,metric,company_name,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,Mar 2021,Mar 2022,Mar 2023
0,Sales,20 Microns Ltd,300.00,312.00,327.00,356.00,357.00,392.00,427.00,480.00,529.00,484.00,613.0,702.00
1,Expenses,20 Microns Ltd,264.00,273.00,297.00,326.00,310.00,337.00,367.00,411.00,463.00,425.00,534.0,616.00
2,Operating Profit,20 Microns Ltd,36.00,39.00,31.00,30.00,46.00,56.00,60.00,69.00,66.00,59.00,79.0,86.00
3,OPM %,20 Microns Ltd,12.00,12.00,9.00,8.00,13.00,14.00,14.00,14.00,12.00,12.00,13.0,12.00
4,Other Income,20 Microns Ltd,2.00,-5.00,2.00,4.00,4.00,2.00,1.00,2.00,3.00,2.00,2.0,3.00
5,Interest,20 Microns Ltd,16.00,18.00,24.00,27.00,25.00,24.00,22.00,22.00,22.00,25.00,20.0,18.00
6,Depreciation,20 Microns Ltd,7.00,8.00,11.00,11.00,10.00,10.00,10.00,10.00,13.00,14.00,14.0,14.00
7,Profit before tax,20 Microns Ltd,16.00,8.00,-2.00,-3.00,14.00,23.00,28.00,38.00,35.00,22.00,48.0,57.00
8,Tax %,20 Microns Ltd,29.00,37.00,-19.00,16.00,24.00,31.00,32.00,35.00,30.00,-6.00,27.0,27.00
9,Net Profit,20 Microns Ltd,11.00,5.00,-2.00,-2.00,11.00,16.00,19.00,25.00,24.00,23.00,35.0,42.00
10,EPS in Rs,20 Microns Ltd,3.85,1.51,-0.68,-0.74,3.11,4.49,5.34,7.08,6.84,6.51,9.8,11.85

In [10]:
df_filtered.shape

(49401, 14)

In [11]:
df_long = pd.melt(df_filtered,id_vars=['metric','company_name'],var_name='financial_year',value_name='value')

In [12]:
df_long.head()

             metric    company_name financial_year  value
0             Sales  20 Microns Ltd       Mar 2012  300.0
1          Expenses  20 Microns Ltd       Mar 2012  264.0
2  Operating Profit  20 Microns Ltd       Mar 2012   36.0
3             OPM %  20 Microns Ltd       Mar 2012   12.0
4      Other Income  20 Microns Ltd       Mar 2012    2.0

In [13]:
df_long.shape

(592812, 4)

In [14]:
df_long['financial_year'] = (
    df_long['financial_year']
    .str.replace('Mar ', '')
    .astype(int)
)

In [15]:
df_long.head()

             metric    company_name  financial_year  value
0             Sales  20 Microns Ltd            2012  300.0
1          Expenses  20 Microns Ltd            2012  264.0
2  Operating Profit  20 Microns Ltd            2012   36.0
3             OPM %  20 Microns Ltd            2012   12.0
4      Other Income  20 Microns Ltd            2012    2.0

In [16]:
df_long.dtypes

metric             object
company_name       object
financial_year      int64
value             float64
dtype: object

In [17]:
df_long.head(80000)

                  metric         company_name  financial_year   value
0                  Sales       20 Microns Ltd            2012  300.00
1               Expenses       20 Microns Ltd            2012  264.00
2       Operating Profit       20 Microns Ltd            2012   36.00
3                  OPM %       20 Microns Ltd            2012   12.00
4           Other Income       20 Microns Ltd            2012    2.00
...                  ...                  ...             ...     ...
79995              OPM %  P.M. Telelinnks Ltd            2013   -1.18
79996       Other Income  P.M. Telelinnks Ltd            2013    0.90
79997           Interest  P.M. Telelinnks Ltd            2013    0.00
79998       Depreciation  P.M. Telelinnks Ltd            2013    0.00
79999  Profit before tax  P.M. Telelinnks Ltd            2013    0.47

[80000 rows x 4 columns]

In [26]:
important_metrics = [
    'Sales',
    'Expenses',
    'Operating Profit',
    'Net Profit',
    'EPS in Rs',
    'Interest',
    'Depreciation',
    'Profit before tax'
]

In [27]:
df_long = df_long[df_long['metric'].isin(important_metrics)]

In [30]:
df_long = df_long.dropna(subset=['value'])

In [32]:
df_long.dropna(subset=['value'])

                   metric        company_name  financial_year   value
0                   Sales      20 Microns Ltd            2012  300.00
1                Expenses      20 Microns Ltd            2012  264.00
2        Operating Profit      20 Microns Ltd            2012   36.00
5                Interest      20 Microns Ltd            2012   16.00
6            Depreciation      20 Microns Ltd            2012    7.00
...                   ...                 ...             ...     ...
592806           Interest  Zydus Wellness Ltd            2023   16.00
592807       Depreciation  Zydus Wellness Ltd            2023   25.00
592808  Profit before tax  Zydus Wellness Ltd            2023  291.00
592810         Net Profit  Zydus Wellness Ltd            2023  310.00
592811          EPS in Rs  Zydus Wellness Ltd            2023   48.78

[348870 rows x 4 columns]

In [33]:
df_pivot = df_long.pivot_table(index=['company_name','financial_year'],
                               columns='metric',
                               values='value').reset_index()

In [34]:
df_pivot.head()

metric,company_name,financial_year,Depreciation,EPS in Rs,Expenses,Interest,Net Profit,Operating Profit,Profit before tax,Sales
0,20 Microns Ltd,2012,7.0,3.85,264.0,16.0,11.0,36.0,16.0,300.0
1,20 Microns Ltd,2013,8.0,1.51,273.0,18.0,5.0,39.0,8.0,312.0
2,20 Microns Ltd,2014,11.0,-0.68,297.0,24.0,-2.0,31.0,-2.0,327.0
3,20 Microns Ltd,2015,11.0,-0.74,326.0,27.0,-2.0,30.0,-3.0,356.0
4,20 Microns Ltd,2016,10.0,3.11,310.0,25.0,11.0,46.0,14.0,357.0

In [35]:
df_pivot.columns.name = None

In [36]:
df_pivot.columns = (df_pivot.columns.str.lower().str.replace(' ','_'))

In [39]:
df_pivot.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11

In [40]:
df_pivot = df_pivot[
    [
        'company_name',
        'financial_year',
        'sales',
        'expenses',
        'operating_profit',
        'interest',
        'depreciation',
        'profit_before_tax',
        'net_profit',
        'eps_in_rs'
    ]
]

In [41]:
df_pivot.to_csv(
    '../data/processed/financials_clean.csv',
    index=False
)

In [43]:
df_pivot.shape

(43910, 10)