In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/processed/financials_clean.csv')

In [3]:
df.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11

In [4]:
df.shape

(43910, 10)

In [5]:
df['profit_margin'] = round((df['net_profit']/df['sales'])*100,2)

In [6]:
df[['company_name','financial_year','profit_margin']].head()

     company_name  financial_year  profit_margin
0  20 Microns Ltd            2012           3.67
1  20 Microns Ltd            2013           1.60
2  20 Microns Ltd            2014          -0.61
3  20 Microns Ltd            2015          -0.56
4  20 Microns Ltd            2016           3.08

In [7]:
df.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs,profit_margin
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85,3.67
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51,1.60
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68,-0.61
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74,-0.56
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11,3.08

In [8]:
df['opm']=round((df['operating_profit']/df['sales'])*100,2)

In [9]:
df.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs,profit_margin,opm
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85,3.67,12.00
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51,1.60,12.50
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68,-0.61,9.48
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74,-0.56,8.43
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11,3.08,12.89

In [10]:
df['expense_ratio']=round(df['expenses']/df['sales']*100,2)

In [11]:
df.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs,profit_margin,opm,expense_ratio
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85,3.67,12.00,88.00
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51,1.60,12.50,87.50
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68,-0.61,9.48,90.83
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74,-0.56,8.43,91.57
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11,3.08,12.89,86.83

In [12]:
df['interest_coverage'] = round(
    df['operating_profit'] / df['interest'],
    2
)

In [13]:
df.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs,profit_margin,opm,expense_ratio,interest_coverage
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85,3.67,12.00,88.00,2.25
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51,1.60,12.50,87.50,2.17
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68,-0.61,9.48,90.83,1.29
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74,-0.56,8.43,91.57,1.11
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11,3.08,12.89,86.83,1.84

In [14]:
df['interest_burden_ratio'] = round(
    (df['interest'] / df['sales']) * 100,
    2
)

In [15]:
df['tax_burden_ratio'] = round(
    (df['net_profit'] / df['profit_before_tax']) * 100,
    2
)

In [16]:
df.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs,profit_margin,opm,expense_ratio,interest_coverage,interest_burden_ratio,tax_burden_ratio
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85,3.67,12.00,88.00,2.25,5.33,68.75
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51,1.60,12.50,87.50,2.17,5.77,62.50
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68,-0.61,9.48,90.83,1.29,7.34,100.00
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74,-0.56,8.43,91.57,1.11,7.58,66.67
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11,3.08,12.89,86.83,1.84,7.00,78.57

In [17]:
df = df.sort_values(['company_name','financial_year'])

In [18]:
df['revenue_growth']=round(df.groupby('company_name')['sales'].pct_change(fill_method=None)*100,2)

In [19]:
df[
    [
        'company_name',
        'financial_year',
        'sales',
        'revenue_growth'
    ]
].head(15)

       company_name  financial_year   sales  revenue_growth
0    20 Microns Ltd            2012   300.0             NaN
1    20 Microns Ltd            2013   312.0            4.00
2    20 Microns Ltd            2014   327.0            4.81
3    20 Microns Ltd            2015   356.0            8.87
4    20 Microns Ltd            2016   357.0            0.28
5    20 Microns Ltd            2017   392.0            9.80
6    20 Microns Ltd            2018   427.0            8.93
7    20 Microns Ltd            2019   480.0           12.41
8    20 Microns Ltd            2020   529.0           10.21
9    20 Microns Ltd            2021   484.0           -8.51
10   20 Microns Ltd            2022   613.0           26.65
11   20 Microns Ltd            2023   702.0           14.52
12  360 ONE WAM Ltd            2018  1705.0             NaN
13  360 ONE WAM Ltd            2019  1578.0           -7.45
14  360 ONE WAM Ltd            2020  1521.0           -3.61

In [20]:
df['profit_growth'] = round(df.groupby('company_name')['net_profit'].pct_change(fill_method = None)*100,2)

In [21]:
df.head(15)

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs,profit_margin,opm,expense_ratio,interest_coverage,interest_burden_ratio,tax_burden_ratio,revenue_growth,profit_growth
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85,3.67,12.00,88.00,2.25,5.33,68.75,NaN,NaN
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51,1.60,12.50,87.50,2.17,5.77,62.50,4.00,-54.55
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68,-0.61,9.48,90.83,1.29,7.34,100.00,4.81,-140.00
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74,-0.56,8.43,91.57,1.11,7.58,66.67,8.87,0.00
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11,3.08,12.89,86.83,1.84,7.00,78.57,0.28,-650.00
5,20 Microns Ltd,2017,392.0,337.0,56.0,24.0,10.0,23.0,16.0,4.49,4.08,14.29,85.97,2.33,6.12,69.57,9.80,45.45
6,20 Microns Ltd,2018,427.0,367.0,60.0,22.0,10.0,28.0,19.0,5.34,4.45,14.05,85.95,2.73,5.15,67.86,8.93,18.75
7,20 Microns Ltd,2019,480.0,411.0,69.0,22.0,10.0,38.0,25.0,7.08,5.21,14.37,85.62,3.14,4.58,65.79,12.41,31.58
8,20 Microns Ltd,2020,529.0,463.0,66.0,22.0,13.0,35.0,24.0,6.84,4.54,12.48,87.52,3.00,4.16,68.57,10.21,-4.00
9,20 Microns Ltd,2021,484.0,425.0,59.0,25.0,14.0,22.0,23.0,6.51,4.75,12.19,87.81,2.36,5.17,104.55,-8.51,-4.17
10,20 Microns Ltd,2022,613.0,534.0,79.0,20.0,14.0,48.0,35.0,9.80,5.71,12.89,87.11,3.95,3.26,72.92,26.65,52.17
11,20 Microns Ltd,2023,702.0,616.0,86.0,18.0,14.0,57.0,42.0,11.85,5.98,12.25,87.75,4.78,2.56,73.68,14.52,20.00
12,360 ONE WAM Ltd,2018,1705.0,652.0,1053.0,559.0,14.0,490.0,380.0,NaN,22.29,61.76,38.24,1.88,32.79,77.55,NaN,NaN
13,360 ONE WAM Ltd,2019,1578.0,589.0,990.0,431.0,22.0,538.0,375.0,NaN,23.76,62.74,37.33,2.30,27.31,69.70,-7.45,-1.32
14,360 ONE WAM Ltd,2020,1521.0,698.0,823.0,502.0,41.0,286.0,201.0,5.77,13.21,54.11,45.89,1.64,33.00,70.28,-3.61,-46.40

In [22]:
cagr_df = df.groupby('company_name').agg({'financial_year':['min','max'],'sales':['first','last']})

In [23]:
cagr_df.head()

                     financial_year          sales
                                min   max    first     last
company_name
20 Microns Ltd                 2012  2023   300.00   702.00
360 ONE WAM Ltd                2018  2023  1705.00  2059.00
3B Blackbio DX Ltd             2012  2023    21.00    62.00
3M India Ltd                   2012  2023  1405.00  3733.00
3P Land Holdings Ltd           2012  2023   170.54     2.52

In [24]:
cagr_df.columns = [
    'start_year',
    'end_year',
    'beginning_sales',
    'ending_sales'
]

In [25]:
cagr_df.head()

                      start_year  end_year  beginning_sales  ending_sales
company_name
20 Microns Ltd              2012      2023           300.00        702.00
360 ONE WAM Ltd             2018      2023          1705.00       2059.00
3B Blackbio DX Ltd          2012      2023            21.00         62.00
3M India Ltd                2012      2023          1405.00       3733.00
3P Land Holdings Ltd        2012      2023           170.54          2.52

In [26]:
cagr_df['years'] = (
    cagr_df['end_year']
    - cagr_df['start_year']
)

In [27]:
cagr_df['cagr']=round(((cagr_df['ending_sales']/cagr_df['beginning_sales'])**(1/cagr_df['years'])-1)*100 ,4)

In [28]:
cagr_df.head()

,start_year,end_year,beginning_sales,ending_sales,years,cagr
company_name,,,,,,
20 Microns Ltd,2012,2023,300.00,702.00,11,8.0351
360 ONE WAM Ltd,2018,2023,1705.00,2059.00,5,3.8452
3B Blackbio DX Ltd,2012,2023,21.00,62.00,11,10.3425
3M India Ltd,2012,2023,1405.00,3733.00,11,9.2899
3P Land Holdings Ltd,2012,2023,170.54,2.52,11,-31.8293

In [29]:
df = df.merge(
    cagr_df[['cagr']],
    on='company_name',
    how='left'
)

In [30]:
df.head()

,company_name,financial_year,sales,expenses,operating_profit,interest,depreciation,profit_before_tax,net_profit,eps_in_rs,profit_margin,opm,expense_ratio,interest_coverage,interest_burden_ratio,tax_burden_ratio,revenue_growth,profit_growth,cagr
0,20 Microns Ltd,2012,300.0,264.0,36.0,16.0,7.0,16.0,11.0,3.85,3.67,12.00,88.00,2.25,5.33,68.75,NaN,NaN,8.0351
1,20 Microns Ltd,2013,312.0,273.0,39.0,18.0,8.0,8.0,5.0,1.51,1.60,12.50,87.50,2.17,5.77,62.50,4.00,-54.55,8.0351
2,20 Microns Ltd,2014,327.0,297.0,31.0,24.0,11.0,-2.0,-2.0,-0.68,-0.61,9.48,90.83,1.29,7.34,100.00,4.81,-140.00,8.0351
3,20 Microns Ltd,2015,356.0,326.0,30.0,27.0,11.0,-3.0,-2.0,-0.74,-0.56,8.43,91.57,1.11,7.58,66.67,8.87,0.00,8.0351
4,20 Microns Ltd,2016,357.0,310.0,46.0,25.0,10.0,14.0,11.0,3.11,3.08,12.89,86.83,1.84,7.00,78.57,0.28,-650.00,8.0351

In [35]:
df.shape

(43910, 19)

In [39]:
df.to_csv('../data/processed/financials_final_kpis.csv',index = False)